build: off

environment:
  GOPATH: c:\gopath
  GO111MODULE: on
  PATH: C:\msys64\mingw64\bin;%PATH%

stack: go 1.12.3

before_test:
  - SET GO111MODULE=off
  - go get -u github.com/ory/go-acc
  - SET GO111MODULE=on

test_script:
  - C:\gopath\bin\go-acc ./pkg/... -- -race

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -t 3f455cbc-75ca-4ab2-a50a-8e37557bb938
