language: go

os:
  - linux
  - osx

go:
  - 1.12.x
  - master

env:
  - GO111MODULE=on

before_install:
  - echo $TRAVIS_OS_NAME
  # Linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update           ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libgtk-3-dev ; fi
  # macOS
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew update                       ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew install gtk+3                ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then ulimit -n 8192                    ; fi
  - go get modernc.org/goyacc
  - make -C pkg/core/parser

script:
  - go test -v ./...
