language: go
os:
  - linux
  - osx
# Ubuntu 18.04を使用する
dist: bionic
go:
  - 1.12.x
  - master
env: GO111MODULE=on
script: go test ./pkg/...

jobs:
  include:
    - stage: build
      os: linux
      dist: bionic
      go: 1.12.x
      env: GO111MODULE=on
      before_script: scripts/install_prerequisites_linux.sh
      script: make
    - stage: build
      os: linux
      dist: bionic
      go: master
      env: GO111MODULE=on
      before_script: scripts/install_prerequisites_linux.sh
      script: make
    - stage: build
      os: osx
      go: 1.12.x
      env: GO111MODULE=on
      before_script: scripts/install_prerequisites_osx.sh
      script: make
    - stage: build
      os: osx
      go: master
      env: GO111MODULE=on
      before_script: scripts/install_prerequisites_osx.sh
      script: make
